// AUTO-GENERATED from the ATK HUB web bundle (hub.atk.pro v3.2.27,
// static/index-F-MYsmWR.js). Do not edit by hand; re-run the extractor.
//
// Identity model (matches the vendor app):
//  - Primary key is USB vendorId:productId.
//  - CID/MID (command 0x10) is NOT unique: 36 (cid,mid) pairs are shared by
//    two or more distinct models.
//  - 4 vendorId:productId pairs are ALSO shared and disambiguated only by
//    CID/MID (all under 0x3554: f506, f50a, f58c, f58f).
//  - Resolve with atkDeviceForHid(), passing the runtime CID/MID when known.
//
// `features` mirrors the vendor filter flags; an absent flag means the vendor
// default (feature present). Semantics are inferred from vendor field names.

export type AtkCatalogSensor =
  | "PAW3950Ultra"
  | "PAW3950DM"
  | "PAW3950"
  | "PAW3955Master"
  | "PAW3395Ultra"
  | "PAW3395"
  | "PAW3395SE"
  | "PAW3315"
  | "PAW3311"
  | "PAW3320"
  | "CORE26K";

/** Per-device capability flags from the vendor filter table. */
export interface AtkDeviceFeatures {
  /** Identity is resolved from CID/MID at runtime. */
  identifyByCidMid?: boolean;
  /** 54H20 MCU variant. */
  is54H20?: boolean;
  /** NearLink (NK) wireless transport. */
  isNearlink?: boolean;
  /** Middle button doubles as a DPI button. */
  middleDpiButton?: boolean;
  /** No "Shard MAX" / athletics-max sensor mode. */
  noAthleticsMax?: boolean;
  /** No bottom (underside) button slot. */
  noBottomButton?: boolean;
  /** No DPI indicator LED colour control. */
  noDpiRGB?: boolean;
  /** No long-range / far-distance mode. */
  noFarDistance?: boolean;
  /** No sensor angle tuning. */
  noSensorAngle?: boolean;
  /** Do not show battery/power level. */
  noShowPower?: boolean;
  /** No independent X/Y DPI axes. */
  noXyDpi?: boolean;
  /** Key debounce has no 0 ms option. */
  noZeroKeyDebounce?: boolean;
  /** Exposes a DPI on/off toggle. */
  supportDpiToggle?: boolean;
  /** Firmware for mouse + receiver upgrades together. */
  upgradeTogether?: boolean;
}

export interface AtkDeviceDescriptor {
  vendorId: number;
  productId: number;
  brand: "ATK" | "VXE";
  model: string;
  sensor: AtkCatalogSensor | null;
  /** Vendor CID/MID ("cid,mid"). NOT unique across models. */
  cidMid: string | null;
  /** Vendor firmware mark (e.g. "f1", "a9", "x1"). */
  firmwareMark: string | null;
  usagePage: number | null;
  usage: number | null;
  features: AtkDeviceFeatures;
}

export const ATK_MOUSE_DEVICES: readonly AtkDeviceDescriptor[] = [
  {
    vendorId: 0x3554,
    productId: 0xf502,
    brand: "ATK",
    model: "ATK Dragonfly F1 PRO",
    sensor: "PAW3395",
    cidMid: "2,1",
    firmwareMark: "f1-pro",
    usagePage: 65284,
    usage: 2,
    features: { identifyByCidMid: true },
  },
  {
    vendorId: 0x3554,
    productId: 0xf506,
    brand: "ATK",
    model: "ATK Dragonfly F1 MOBA",
    sensor: "PAW3395",
    cidMid: "2,5",
    firmwareMark: "f1-moba",
    usagePage: 65284,
    usage: 2,
    features: { identifyByCidMid: true },
  },
  {
    vendorId: 0x3554,
    productId: 0xf506,
    brand: "ATK",
    model: "ATK Dragonfly F1 PRO MAX",
    sensor: "PAW3395",
    cidMid: "2,3",
    firmwareMark: "f1-pro-max",
    usagePage: 65284,
    usage: 2,
    features: { identifyByCidMid: true },
  },
  {
    vendorId: 0x3554,
    productId: 0xf506,
    brand: "ATK",
    model: "ATK Dragonfly F1 PRO MAX Elden",
    sensor: "PAW3395",
    cidMid: "2,48",
    firmwareMark: "f1-pro-max-elden",
    usagePage: 65284,
    usage: 2,
    features: { identifyByCidMid: true },
  },
  {
    vendorId: 0x3554,
    productId: 0xf506,
    brand: "ATK",
    model: "ATK Dragonfly F1 PRO MAX JOJO",
    sensor: "PAW3395",
    cidMid: "2,52",
    firmwareMark: "f1-pro-max-jojo",
    usagePage: 65284,
    usage: 2,
    features: { identifyByCidMid: true },
  },
  {
    vendorId: 0x3554,
    productId: 0xf50a,
    brand: "ATK",
    model: "ATK Dragonfly Dragonfly F1S",
    sensor: "PAW3395",
    cidMid: "2,20",
    firmwareMark: "f1-s",
    usagePage: 65284,
    usage: 2,
    features: { identifyByCidMid: true },
  },
  {
    vendorId: 0x3554,
    productId: 0xf50a,
    brand: "ATK",
    model: "ATK Dragonfly F1S",
    sensor: "PAW3395",
    cidMid: "2,19",
    firmwareMark: "f1-s",
    usagePage: 65284,
    usage: 2,
    features: { identifyByCidMid: true },
  },
  {
    vendorId: 0x3554,
    productId: 0xf58c,
    brand: "VXE",
    model: "VXE R1 PRO",
    sensor: "PAW3395",
    cidMid: "2,7",
    firmwareMark: "r1-pro",
    usagePage: 65284,
    usage: 2,
    features: { identifyByCidMid: true },
  },
  {
    vendorId: 0x3554,
    productId: 0xf58c,
    brand: "VXE",
    model: "VXE R1 PRO MAX",
    sensor: "PAW3395",
    cidMid: "2,27",
    firmwareMark: "r1-pro-max",
    usagePage: 65284,
    usage: 2,
    features: { identifyByCidMid: true },
  },
  {
    vendorId: 0x3554,
    productId: 0xf58f,
    brand: "VXE",
    model: "VXE R1",
    sensor: "PAW3395",
    cidMid: "2,11",
    firmwareMark: "r1",
    usagePage: 65284,
    usage: 2,
    features: { identifyByCidMid: true },
  },
  {
    vendorId: 0x3554,
    productId: 0xf58f,
    brand: "VXE",
    model: "VXE R1SE",
    sensor: "PAW3395SE",
    cidMid: "2,29",
    firmwareMark: "r1-se",
    usagePage: 65284,
    usage: 2,
    features: { identifyByCidMid: true },
  },
  {
    vendorId: 0x3554,
    productId: 0xf58f,
    brand: "VXE",
    model: "VXE R1SE+",
    sensor: "PAW3395SE",
    cidMid: "2,31",
    firmwareMark: "r1-se+",
    usagePage: 65284,
    usage: 2,
    features: { identifyByCidMid: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1014,
    brand: "ATK",
    model: "ATK F1 PRO",
    sensor: "PAW3950",
    cidMid: "2,36",
    firmwareMark: "f1",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x1015,
    brand: "ATK",
    model: "ATK F1 PRO MAX",
    sensor: "PAW3950",
    cidMid: "2,37",
    firmwareMark: "f1",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x1016,
    brand: "ATK",
    model: "ATK X1 PRO",
    sensor: "PAW3950",
    cidMid: "2,38",
    firmwareMark: "x1",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x1017,
    brand: "ATK",
    model: "ATK X1 PRO MAX",
    sensor: "PAW3950",
    cidMid: "2,39",
    firmwareMark: "x1",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x1018,
    brand: "ATK",
    model: "ATK Z1 PRO",
    sensor: "PAW3950",
    cidMid: "2,40",
    firmwareMark: "z1",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x1019,
    brand: "ATK",
    model: "ATK Z1 PRO MAX",
    sensor: "PAW3950",
    cidMid: "2,41",
    firmwareMark: "z1",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x102e,
    brand: "ATK",
    model: "ATK F1 Ultimate",
    sensor: "PAW3950Ultra",
    cidMid: "2,42",
    firmwareMark: "f1",
    usagePage: 65284,
    usage: 2,
    features: { noBottomButton: true, noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x102f,
    brand: "ATK",
    model: "ATK X1 Ultra",
    sensor: "PAW3950Ultra",
    cidMid: "2,43",
    firmwareMark: "x1",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x1030,
    brand: "ATK",
    model: "ATK FIERCE X",
    sensor: "PAW3950Ultra",
    cidMid: "2,44",
    firmwareMark: "fierce-x",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x103c,
    brand: "ATK",
    model: "ATK F1 Ultra",
    sensor: "PAW3950Ultra",
    cidMid: "2,45",
    firmwareMark: "f1",
    usagePage: 65284,
    usage: 2,
    features: { noBottomButton: true, noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x103d,
    brand: "ATK",
    model: "ATK X1 Ultimate",
    sensor: "PAW3950Ultra",
    cidMid: "2,46",
    firmwareMark: "x1",
    usagePage: 65284,
    usage: 2,
    features: { noBottomButton: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x103e,
    brand: "ATK",
    model: "MAD R MAJOR",
    sensor: "PAW3950",
    cidMid: "2,47",
    firmwareMark: "mad-r",
    usagePage: 65284,
    usage: 2,
    features: { noBottomButton: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x103f,
    brand: "ATK",
    model: "MAD R",
    sensor: "PAW3395",
    cidMid: "2,49",
    firmwareMark: "mad-r",
    usagePage: 65284,
    usage: 2,
    features: { noBottomButton: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1045,
    brand: "ATK",
    model: "ATK F1 EXTREME",
    sensor: "PAW3950Ultra",
    cidMid: "2,50",
    firmwareMark: "f1",
    usagePage: 65284,
    usage: 2,
    features: { noBottomButton: true, noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x104a,
    brand: "ATK",
    model: "ATK Z1 Ultra",
    sensor: "PAW3950Ultra",
    cidMid: "2,53",
    firmwareMark: "z1",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x104b,
    brand: "ATK",
    model: "MAD R +",
    sensor: "PAW3395",
    cidMid: "2,54",
    firmwareMark: "mad-r",
    usagePage: 65284,
    usage: 2,
    features: { noBottomButton: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x104c,
    brand: "ATK",
    model: "MAD R MAJOR+",
    sensor: "PAW3950",
    cidMid: "2,55",
    firmwareMark: "mad-r",
    usagePage: 65284,
    usage: 2,
    features: { noBottomButton: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x105b,
    brand: "ATK",
    model: "ATK F1 LEVIATAN",
    sensor: "PAW3950Ultra",
    cidMid: "2,56",
    firmwareMark: "f1",
    usagePage: 65284,
    usage: 2,
    features: { noBottomButton: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1065,
    brand: "VXE",
    model: "VXE R1 NK",
    sensor: "PAW3395SE",
    cidMid: "2,57",
    firmwareMark: "r1",
    usagePage: 65284,
    usage: 2,
    features: { noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1066,
    brand: "VXE",
    model: "VXE R1 NK",
    sensor: "PAW3395SE",
    cidMid: "2,57",
    firmwareMark: "r1",
    usagePage: 65284,
    usage: 2,
    features: { noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1084,
    brand: "VXE",
    model: "VXE R1S+",
    sensor: "PAW3311",
    cidMid: "2,63",
    firmwareMark: "r1",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x1086,
    brand: "ATK",
    model: "ATK U2 MINI",
    sensor: "PAW3950",
    cidMid: "2,64",
    firmwareMark: "u2",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x1087,
    brand: "ATK",
    model: "ATK U2 Ultimate",
    sensor: "PAW3950Ultra",
    cidMid: "2,65",
    firmwareMark: "u2",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x10ac,
    brand: "ATK",
    model: "ATK U2 Ultra",
    sensor: "PAW3950",
    cidMid: "2,66",
    firmwareMark: "u2",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x10c7,
    brand: "VXE",
    model: "VXE R1 NK",
    sensor: "PAW3395SE",
    cidMid: "2,67",
    firmwareMark: "r1",
    usagePage: 65284,
    usage: 2,
    features: { noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x10c8,
    brand: "VXE",
    model: "VXE R1 NK",
    sensor: "PAW3395SE",
    cidMid: "2,67",
    firmwareMark: "r1",
    usagePage: 65284,
    usage: 2,
    features: { noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x10d8,
    brand: "ATK",
    model: "ATK X1",
    sensor: "PAW3395",
    cidMid: "1,1",
    firmwareMark: "x1",
    usagePage: 65296,
    usage: 1,
    features: { noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x10e7,
    brand: "VXE",
    model: "VXE V3 NK",
    sensor: "PAW3311",
    cidMid: "2,72",
    firmwareMark: "v3",
    usagePage: 65284,
    usage: 2,
    features: { middleDpiButton: true, noFarDistance: true, noShowPower: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x10e8,
    brand: "VXE",
    model: "VXE V3 PRO NK",
    sensor: "PAW3395SE",
    cidMid: "2,73",
    firmwareMark: "v3",
    usagePage: 65284,
    usage: 2,
    features: { middleDpiButton: true, noFarDistance: true, noShowPower: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x10e9,
    brand: "ATK",
    model: "ATK X1 EXTREME",
    sensor: "PAW3950Ultra",
    cidMid: "2,70",
    firmwareMark: "x1",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x10ec,
    brand: "ATK",
    model: "ATK U2 Pro",
    sensor: "PAW3395Ultra",
    cidMid: "2,1",
    firmwareMark: "u2",
    usagePage: 65296,
    usage: 1,
    features: { noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x10fd,
    brand: "ATK",
    model: "ATK Y9 PRO MAX",
    sensor: "PAW3950",
    cidMid: "2,108",
    firmwareMark: "y9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1106,
    brand: "ATK",
    model: "ATK X1 S NK",
    sensor: "PAW3395",
    cidMid: "2,76",
    firmwareMark: "x1",
    usagePage: 65284,
    usage: 2,
    features: { noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1107,
    brand: "ATK",
    model: "ATK X1 SE NK",
    sensor: "PAW3395SE",
    cidMid: "2,77",
    firmwareMark: "x1",
    usagePage: 65284,
    usage: 2,
    features: { noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x110d,
    brand: "ATK",
    model: "ATK U2 Plus NK",
    sensor: "PAW3395",
    cidMid: "2,78",
    firmwareMark: "u2",
    usagePage: 65284,
    usage: 2,
    features: { noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x110e,
    brand: "ATK",
    model: "ATK U2 NK",
    sensor: "PAW3395SE",
    cidMid: "2,79",
    firmwareMark: "u2",
    usagePage: 65284,
    usage: 2,
    features: { noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1115,
    brand: "ATK",
    model: "ATK A9 Plus NK",
    sensor: "PAW3395",
    cidMid: "2,83",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true, noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1116,
    brand: "ATK",
    model: "ATK A9 NK",
    sensor: "PAW3395SE",
    cidMid: "2,84",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true, noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1117,
    brand: "ATK",
    model: "ATK A9 Pro Max",
    sensor: "PAW3395Ultra",
    cidMid: "2,85",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1119,
    brand: "ATK",
    model: "ATK A9 Ultra",
    sensor: "PAW3950Ultra",
    cidMid: "2,87",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x112d,
    brand: "ATK",
    model: "ATK A9 Pro",
    sensor: "PAW3395Ultra",
    cidMid: "2,2",
    firmwareMark: "a9",
    usagePage: 65296,
    usage: 1,
    features: { noDpiRGB: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x112e,
    brand: "ATK",
    model: "ATK Y9 Pro",
    sensor: "PAW3395Ultra",
    cidMid: "2,3",
    firmwareMark: "y9",
    usagePage: 65296,
    usage: 1,
    features: { noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1135,
    brand: "ATK",
    model: "ATK A9 SE NK",
    sensor: "PAW3311",
    cidMid: "2,88",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true, noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x113e,
    brand: "ATK",
    model: "ATK X1 Lite",
    sensor: "PAW3395",
    cidMid: "2,89",
    firmwareMark: "x1",
    usagePage: 65284,
    usage: 2,
    features: { noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x113f,
    brand: "ATK",
    model: "ATK X1E",
    sensor: "PAW3395SE",
    cidMid: "2,90",
    firmwareMark: "x1",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x1147,
    brand: "ATK",
    model: "ATK A9 PRO MAX",
    sensor: "PAW3395Ultra",
    cidMid: "0,0",
    firmwareMark: "a9",
    usagePage: 65440,
    usage: 2,
    features: { noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1149,
    brand: "ATK",
    model: "ATK U2 SE NK",
    sensor: "PAW3311",
    cidMid: "2,92",
    firmwareMark: "u2",
    usagePage: 65284,
    usage: 2,
    features: { noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x114a,
    brand: "ATK",
    model: "DRAGONFLY F1 V2 Plus NK",
    sensor: "PAW3395",
    cidMid: "2,93",
    firmwareMark: "f1",
    usagePage: 65284,
    usage: 2,
    features: { noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x114b,
    brand: "ATK",
    model: "DRAGONFLY F1 V2 NK",
    sensor: "PAW3395SE",
    cidMid: "2,94",
    firmwareMark: "f1",
    usagePage: 65284,
    usage: 2,
    features: { noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x114c,
    brand: "ATK",
    model: "DRAGONFLY F1 V2 SE NK",
    sensor: "PAW3311",
    cidMid: "2,95",
    firmwareMark: "f1",
    usagePage: 65284,
    usage: 2,
    features: { noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1154,
    brand: "ATK",
    model: "ATK ZERO",
    sensor: "PAW3950Ultra",
    cidMid: "1,1",
    firmwareMark: "zero",
    usagePage: 65285,
    usage: 1,
    features: { noBottomButton: true, noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1157,
    brand: "ATK",
    model: "ATK A9",
    sensor: "PAW3395SE",
    cidMid: "2,99",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1158,
    brand: "ATK",
    model: "ATK U2 Pro Max",
    sensor: "PAW3395Ultra",
    cidMid: "2,100",
    firmwareMark: "u2",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x115b,
    brand: "ATK",
    model: "ATK Y9 Plus NK",
    sensor: "PAW3395",
    cidMid: "2,96",
    firmwareMark: "y9",
    usagePage: 65284,
    usage: 2,
    features: { noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x115c,
    brand: "ATK",
    model: "ATK Y9 NK",
    sensor: "PAW3395SE",
    cidMid: "2,97",
    firmwareMark: "y9",
    usagePage: 65284,
    usage: 2,
    features: { noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x115d,
    brand: "ATK",
    model: "ATK Y9 SE NK",
    sensor: "PAW3311",
    cidMid: "2,98",
    firmwareMark: "y9",
    usagePage: 65284,
    usage: 2,
    features: { noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1175,
    brand: "ATK",
    model: "DRAGONFLY F1 V2 Pro",
    sensor: "PAW3395Ultra",
    cidMid: "4,2",
    firmwareMark: "f1",
    usagePage: 65296,
    usage: 1,
    features: { noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x11a0,
    brand: "ATK",
    model: "ATK A9 X",
    sensor: "PAW3395SE",
    cidMid: "2,107",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x11a6,
    brand: "ATK",
    model: "ATK Duckbill Ultra",
    sensor: "PAW3950Ultra",
    cidMid: "1,2",
    firmwareMark: "duckbill",
    usagePage: 65284,
    usage: 2,
    features: { is54H20: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x11aa,
    brand: "ATK",
    model: "ATK U2",
    sensor: "PAW3395SE",
    cidMid: "2,109",
    firmwareMark: "u2",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x11ab,
    brand: "ATK",
    model: "DRAGONFLY F1 V2 PRO MAX",
    sensor: "PAW3395Ultra",
    cidMid: "2,110",
    firmwareMark: "f1",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x11b6,
    brand: "ATK",
    model: "ATK A9 Ultimate",
    sensor: "PAW3950Ultra",
    cidMid: "1,3",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x11cc,
    brand: "ATK",
    model: "ATK ZERO EX",
    sensor: "PAW3950Ultra",
    cidMid: "1,4",
    firmwareMark: "duckbill",
    usagePage: 65284,
    usage: 2,
    features: { is54H20: true, noBottomButton: true, noDpiRGB: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x11cf,
    brand: "ATK",
    model: "ATK Y9 Ultimate",
    sensor: "PAW3950Ultra",
    cidMid: "1,5",
    firmwareMark: "y9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x11d2,
    brand: "VXE",
    model: "VXE R1 UlTRA",
    sensor: "PAW3395",
    cidMid: "2,114",
    firmwareMark: "r1",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x11db,
    brand: "ATK",
    model: "ATK A9 Pro Max 2.0 NK",
    sensor: "PAW3395Ultra",
    cidMid: "2,1",
    firmwareMark: "a9",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noDpiRGB: true, noFarDistance: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x11dd,
    brand: "ATK",
    model: "ATK A9 Ultra Max 2.0",
    sensor: "PAW3395Ultra",
    cidMid: "1,6",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true, noZeroKeyDebounce: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x11e3,
    brand: "ATK",
    model: "ATK F1 EXTREME 2.0",
    sensor: "PAW3950Ultra",
    cidMid: "1,7",
    firmwareMark: "f1",
    usagePage: 65284,
    usage: 2,
    features: { is54H20: true, noBottomButton: true, noDpiRGB: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x11e4,
    brand: "ATK",
    model: "ATK F1 Ultimate 2.0",
    sensor: "PAW3950Ultra",
    cidMid: "1,8",
    firmwareMark: "f1",
    usagePage: 65284,
    usage: 2,
    features: { noBottomButton: true, noDpiRGB: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x11e5,
    brand: "ATK",
    model: "ATK X1 EXTREME 2.0",
    sensor: "PAW3950Ultra",
    cidMid: "1,9",
    firmwareMark: "x1",
    usagePage: 65284,
    usage: 2,
    features: { is54H20: true, noBottomButton: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x11e7,
    brand: "ATK",
    model: "ATK X1 Ultimate 2.0",
    sensor: "PAW3950Ultra",
    cidMid: "1,10",
    firmwareMark: "x1",
    usagePage: 65284,
    usage: 2,
    features: { noBottomButton: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x11ec,
    brand: "ATK",
    model: "ATK X1 Ultra Max 2.0",
    sensor: "PAW3395Ultra",
    cidMid: "1,11",
    firmwareMark: "x1",
    usagePage: 65284,
    usage: 2,
    features: { upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x11ed,
    brand: "ATK",
    model: "ATK F1 Ultra Max 2.0",
    sensor: "PAW3395Ultra",
    cidMid: "1,12",
    firmwareMark: "f1",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x11f0,
    brand: "ATK",
    model: "ATK F1 LEVIATAN 2.0",
    sensor: "PAW3950Ultra",
    cidMid: "1,13",
    firmwareMark: "f1",
    usagePage: 65284,
    usage: 2,
    features: { is54H20: true, noBottomButton: true, noDpiRGB: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x11f2,
    brand: "ATK",
    model: "ATK A9 Ultra Max 2.0 Tri-Mode",
    sensor: "PAW3395Ultra",
    cidMid: "1,15",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true, noZeroKeyDebounce: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x11f3,
    brand: "ATK",
    model: "ATK A9 NB ULTRA",
    sensor: "PAW3950Ultra",
    cidMid: "2,115",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x11f5,
    brand: "ATK",
    model: "ATK U2 Ultimate 2.0",
    sensor: "PAW3950Ultra",
    cidMid: "1,16",
    firmwareMark: "u2",
    usagePage: 65284,
    usage: 2,
    features: { upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x11f6,
    brand: "ATK",
    model: "ATK U2 Mini 2.0",
    sensor: "PAW3950Ultra",
    cidMid: "1,17",
    firmwareMark: "u2",
    usagePage: 65284,
    usage: 2,
    features: { upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x11f7,
    brand: "ATK",
    model: "ATK U2 Ultra Max 2.0",
    sensor: "PAW3395Ultra",
    cidMid: "1,18",
    firmwareMark: "u2",
    usagePage: 65284,
    usage: 2,
    features: { upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x11f9,
    brand: "VXE",
    model: "VXE R1 Ultra",
    sensor: "PAW3395Ultra",
    cidMid: "1,20",
    firmwareMark: "r1",
    usagePage: 65284,
    usage: 2,
    features: { upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1201,
    brand: "ATK",
    model: "ATK Z1 Ultimate 2.0",
    sensor: "PAW3950Ultra",
    cidMid: "1,19",
    firmwareMark: "z1",
    usagePage: 65284,
    usage: 2,
    features: { upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x120a,
    brand: "ATK",
    model: "ATK A9 Air",
    sensor: "PAW3950Ultra",
    cidMid: "1,21",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x120b,
    brand: "ATK",
    model: "ATK X1 EXTREME GT",
    sensor: "PAW3950Ultra",
    cidMid: "1,22",
    firmwareMark: "x1",
    usagePage: 65284,
    usage: 2,
    features: { is54H20: true, noBottomButton: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x120d,
    brand: "ATK",
    model: "ATK Ghost EXTREME",
    sensor: "PAW3950Ultra",
    cidMid: "1,23",
    firmwareMark: "ghost",
    usagePage: 65284,
    usage: 2,
    features: { is54H20: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x120e,
    brand: "ATK",
    model: "ATK Ghost Ultimate",
    sensor: "PAW3950Ultra",
    cidMid: "1,24",
    firmwareMark: "ghost",
    usagePage: 65284,
    usage: 2,
    features: { upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1211,
    brand: "ATK",
    model: "ATK A9 Ultimate 3.0",
    sensor: "PAW3950Ultra",
    cidMid: "1,2",
    firmwareMark: "a9",
    usagePage: 65285,
    usage: 1,
    features: { noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1213,
    brand: "VXE",
    model: "VXE V3 NK",
    sensor: "PAW3311",
    cidMid: "2,5",
    firmwareMark: "v3",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, middleDpiButton: true, noAthleticsMax: true, noDpiRGB: true, noFarDistance: true, noSensorAngle: true, noXyDpi: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1214,
    brand: "VXE",
    model: "VXE V3 PRO NK",
    sensor: "PAW3395SE",
    cidMid: "2,6",
    firmwareMark: "v3",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, middleDpiButton: true, noAthleticsMax: true, noDpiRGB: true, noFarDistance: true, noSensorAngle: true, noXyDpi: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1215,
    brand: "VXE",
    model: "VXE V3 Plus",
    sensor: "PAW3395Ultra",
    cidMid: "2,7",
    firmwareMark: "v3",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, middleDpiButton: true, noAthleticsMax: true, noDpiRGB: true, noFarDistance: true, noSensorAngle: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x121f,
    brand: "VXE",
    model: "VXE R1 S NK",
    sensor: "PAW3311",
    cidMid: "2,117",
    firmwareMark: "r1s",
    usagePage: 65284,
    usage: 2,
    features: { noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1222,
    brand: "ATK",
    model: "ATK A9 SE NK",
    sensor: "PAW3311",
    cidMid: "2,2",
    firmwareMark: "a9",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noAthleticsMax: true, noDpiRGB: true, noFarDistance: true, noSensorAngle: true, noXyDpi: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1223,
    brand: "ATK",
    model: "ATK A9 NK",
    sensor: "PAW3395SE",
    cidMid: "2,3",
    firmwareMark: "a9",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noAthleticsMax: true, noDpiRGB: true, noFarDistance: true, noSensorAngle: true, noXyDpi: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1224,
    brand: "ATK",
    model: "ATK A9 Plus NK",
    sensor: "PAW3395Ultra",
    cidMid: "2,4",
    firmwareMark: "a9",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noAthleticsMax: true, noDpiRGB: true, noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1230,
    brand: "ATK",
    model: "ATK Duckbill EXTREME",
    sensor: "PAW3950Ultra",
    cidMid: "1,25",
    firmwareMark: "duckbill",
    usagePage: 65284,
    usage: 2,
    features: { is54H20: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x123a,
    brand: "ATK",
    model: "ATK Ghost Ultimate",
    sensor: "PAW3950Ultra",
    cidMid: "1,3",
    firmwareMark: "ghost",
    usagePage: 65285,
    usage: 1,
    features: { noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1245,
    brand: "ATK",
    model: "ATK A9 NB",
    sensor: "PAW3395SE",
    cidMid: "2,120",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1248,
    brand: "VXE",
    model: "VXE X3",
    sensor: "PAW3315",
    cidMid: "2,121",
    firmwareMark: "x3",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x1249,
    brand: "VXE",
    model: "VXE X3 Pro",
    sensor: "PAW3395SE",
    cidMid: "2,122",
    firmwareMark: "x3",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x124a,
    brand: "VXE",
    model: "VXE X3 Turbo",
    sensor: "PAW3395SE",
    cidMid: "2,123",
    firmwareMark: "x3",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x124c,
    brand: "VXE",
    model: "VXE R1 NK",
    sensor: "PAW3395SE",
    cidMid: "2,8",
    firmwareMark: "r1",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noAthleticsMax: true, noFarDistance: true, noSensorAngle: true, noXyDpi: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x124d,
    brand: "VXE",
    model: "VXE R1 S NK",
    sensor: "PAW3311",
    cidMid: "2,9",
    firmwareMark: "r1s",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noAthleticsMax: true, noFarDistance: true, noSensorAngle: true, noXyDpi: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x124e,
    brand: "ATK",
    model: "ATK ZERO",
    sensor: "PAW3950Ultra",
    cidMid: "1,26",
    firmwareMark: "zero",
    usagePage: 65284,
    usage: 2,
    features: { noBottomButton: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1251,
    brand: "ATK",
    model: "ATK A9 Mini +",
    sensor: "PAW3955Master",
    cidMid: "1,4",
    firmwareMark: "a9",
    usagePage: 65285,
    usage: 1,
    features: { noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1256,
    brand: "ATK",
    model: "ATK A9 Mini",
    sensor: "PAW3950Ultra",
    cidMid: "1,27",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x125a,
    brand: "ATK",
    model: "ATK A9 Mini",
    sensor: "PAW3950Ultra",
    cidMid: "1,28",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1263,
    brand: "ATK",
    model: "ATK A9 Plus NK",
    sensor: "PAW3950Ultra",
    cidMid: "2,13",
    firmwareMark: "a9",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noAthleticsMax: true, noDpiRGB: true, noFarDistance: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1264,
    brand: "ATK",
    model: "ATK A9 Pro Max 2.0 NK",
    sensor: "PAW3950Ultra",
    cidMid: "2,14",
    firmwareMark: "a9",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noDpiRGB: true, noFarDistance: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1266,
    brand: "ATK",
    model: "ATK X EXTREME",
    sensor: "PAW3950Ultra",
    cidMid: "1,30",
    firmwareMark: "x",
    usagePage: 65284,
    usage: 2,
    features: { is54H20: true, noBottomButton: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1268,
    brand: "ATK",
    model: "ATK A9 Mini",
    sensor: "PAW3950Ultra",
    cidMid: "1,16",
    firmwareMark: "a9",
    usagePage: 65285,
    usage: 1,
    features: { noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1269,
    brand: "ATK",
    model: "ATK A9 Mini +",
    sensor: "PAW3955Master",
    cidMid: "1,31",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x126c,
    brand: "ATK",
    model: "ATK U2 Plus NK",
    sensor: "PAW3950Ultra",
    cidMid: "2,124",
    firmwareMark: "u2",
    usagePage: 65284,
    usage: 2,
    features: { noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x126d,
    brand: "ATK",
    model: "ATK U2 Pro Max",
    sensor: "PAW3950Ultra",
    cidMid: "2,128",
    firmwareMark: "u2",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x126e,
    brand: "ATK",
    model: "ATK F1 Ultra Max 2.0",
    sensor: "PAW3950Ultra",
    cidMid: "1,33",
    firmwareMark: "f1",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x126f,
    brand: "ATK",
    model: "ATK A9 Ultra Max 2.0",
    sensor: "PAW3950Ultra",
    cidMid: "1,38",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true, noZeroKeyDebounce: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1270,
    brand: "ATK",
    model: "ATK A9 Ultra Max 2.0 Tri-Mode",
    sensor: "PAW3950Ultra",
    cidMid: "1,37",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true, noZeroKeyDebounce: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1271,
    brand: "VXE",
    model: "VXE R1",
    sensor: "PAW3950Ultra",
    cidMid: "2,127",
    firmwareMark: "r1",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x1272,
    brand: "VXE",
    model: "VXE R1 PRO",
    sensor: "PAW3950Ultra",
    cidMid: "2,125",
    firmwareMark: "r1",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x1273,
    brand: "VXE",
    model: "VXE R1 PRO MAX",
    sensor: "PAW3950Ultra",
    cidMid: "2,126",
    firmwareMark: "r1",
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x1274,
    brand: "ATK",
    model: "ATK X1 Ultra Max 2.0",
    sensor: "PAW3950Ultra",
    cidMid: "1,32",
    firmwareMark: "x1",
    usagePage: 65284,
    usage: 2,
    features: { upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x127b,
    brand: "VXE",
    model: "VXE V3 PRO Max",
    sensor: "CORE26K",
    cidMid: "2,15",
    firmwareMark: "v3",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, middleDpiButton: true, noAthleticsMax: true, noDpiRGB: true, noFarDistance: true, noSensorAngle: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x127c,
    brand: "ATK",
    model: "ATK X1 Air +",
    sensor: "PAW3955Master",
    cidMid: "1,42",
    firmwareMark: "x1",
    usagePage: 65284,
    usage: 2,
    features: { is54H20: true, noBottomButton: true, supportDpiToggle: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x127e,
    brand: "ATK",
    model: "ATK A9 Ultimate +",
    sensor: "PAW3955Master",
    cidMid: "1,39",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x127f,
    brand: "ATK",
    model: "ATK A9 Air +",
    sensor: "PAW3955Master",
    cidMid: "1,40",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1282,
    brand: "ATK",
    model: "ATK Duckbill ELITE",
    sensor: "PAW3950Ultra",
    cidMid: "`${Rt.WAIZOWL},1`",
    firmwareMark: "duckbill",
    usagePage: 65282,
    usage: 2,
    features: { noDpiRGB: true, noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1285,
    brand: "ATK",
    model: "ATK X1 EXTREME 2.0 +",
    sensor: "PAW3955Master",
    cidMid: "1,45",
    firmwareMark: "x1",
    usagePage: 65284,
    usage: 2,
    features: { is54H20: true, noBottomButton: true, supportDpiToggle: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1286,
    brand: "ATK",
    model: "ATK X1 Ultimate 2.0 +",
    sensor: "PAW3955Master",
    cidMid: "1,46",
    firmwareMark: "x1",
    usagePage: 65284,
    usage: 2,
    features: { noBottomButton: true, supportDpiToggle: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1287,
    brand: "ATK",
    model: "ATK A9 Ultimate +",
    sensor: "PAW3955Master",
    cidMid: "1,9",
    firmwareMark: "a9",
    usagePage: 65285,
    usage: 1,
    features: { noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1288,
    brand: "ATK",
    model: "ATK A9 Air +",
    sensor: "PAW3955Master",
    cidMid: "1,6",
    firmwareMark: "a9",
    usagePage: 65285,
    usage: 1,
    features: { noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1289,
    brand: "ATK",
    model: "ATK ZERO EX +",
    sensor: "PAW3955Master",
    cidMid: "1,47",
    firmwareMark: "zero",
    usagePage: 65284,
    usage: 2,
    features: { is54H20: true, noBottomButton: true, noDpiRGB: true, supportDpiToggle: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x128a,
    brand: "ATK",
    model: "ATK Ghost EXTREME +",
    sensor: "PAW3955Master",
    cidMid: "1,48",
    firmwareMark: "ghost",
    usagePage: 65284,
    usage: 2,
    features: { is54H20: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x128b,
    brand: "ATK",
    model: "ATK Ghost Ultimate +",
    sensor: "PAW3955Master",
    cidMid: "1,49",
    firmwareMark: "ghost",
    usagePage: 65284,
    usage: 2,
    features: { upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x128c,
    brand: "ATK",
    model: "ATK U2 Ultimate 2.0 +",
    sensor: "PAW3955Master",
    cidMid: "1,50",
    firmwareMark: "u2",
    usagePage: 65284,
    usage: 2,
    features: { upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x128d,
    brand: "ATK",
    model: "ATK U2 Mini 2.0 +",
    sensor: "PAW3955Master",
    cidMid: "1,51",
    firmwareMark: "u2",
    usagePage: 65284,
    usage: 2,
    features: { upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x128e,
    brand: "ATK",
    model: "ATK A9 Mini +",
    sensor: "PAW3955Master",
    cidMid: "1,52",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x128f,
    brand: "ATK",
    model: "ATK A9 Ultra Max 2.0 +",
    sensor: "PAW3950Ultra",
    cidMid: "1,7",
    firmwareMark: "a9",
    usagePage: 65285,
    usage: 1,
    features: { noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1292,
    brand: "ATK",
    model: "ATK A9 Ultimate +",
    sensor: "PAW3955Master",
    cidMid: "1,53",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1293,
    brand: "ATK",
    model: "ATK A9 Air +",
    sensor: "PAW3955Master",
    cidMid: "1,54",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1296,
    brand: "ATK",
    model: "ATK PHANTOM ULTIMATE",
    sensor: "PAW3955Master",
    cidMid: "1,55",
    firmwareMark: "phantom",
    usagePage: 65284,
    usage: 2,
    features: { noBottomButton: true, noDpiRGB: true, supportDpiToggle: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1299,
    brand: "ATK",
    model: "ATK X1 SE Nearlink",
    sensor: "PAW3395SE",
    cidMid: "2,16",
    firmwareMark: "x1",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noAthleticsMax: true, noFarDistance: true, noSensorAngle: true, noXyDpi: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x129a,
    brand: "VXE",
    model: "VXE R1 PRO MAX 2.0 NK",
    sensor: "PAW3950Ultra",
    cidMid: "2,17",
    firmwareMark: "r1",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noAthleticsMax: true, noFarDistance: true, noSensorAngle: true, noXyDpi: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x129b,
    brand: "ATK",
    model: "ATK F1 V3 EXTREME +",
    sensor: "PAW3955Master",
    cidMid: "1,58",
    firmwareMark: "f1",
    usagePage: 65284,
    usage: 2,
    features: { is54H20: true, noBottomButton: true, noDpiRGB: true, noShowPower: true, supportDpiToggle: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x129c,
    brand: "ATK",
    model: "ATK F1 Ultimate 2.0 +",
    sensor: "PAW3955Master",
    cidMid: "1,59",
    firmwareMark: "f1",
    usagePage: 65284,
    usage: 2,
    features: { noBottomButton: true, noDpiRGB: true, supportDpiToggle: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x129d,
    brand: "ATK",
    model: "ATK F1 V3 LEVIATAN +",
    sensor: "PAW3955Master",
    cidMid: "1,60",
    firmwareMark: "f1",
    usagePage: 65284,
    usage: 2,
    features: { is54H20: true, noBottomButton: true, noDpiRGB: true, noShowPower: true, supportDpiToggle: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x129e,
    brand: "ATK",
    model: "ATK ZERO +",
    sensor: "PAW3955Master",
    cidMid: "1,8",
    firmwareMark: "zero",
    usagePage: 65285,
    usage: 1,
    features: { noBottomButton: true, noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12a2,
    brand: "ATK",
    model: "ATK X1 Air +",
    sensor: "PAW3955Master",
    cidMid: "1,61",
    firmwareMark: "x1",
    usagePage: 65284,
    usage: 2,
    features: { noBottomButton: true, supportDpiToggle: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12a7,
    brand: "ATK",
    model: "ATK F1 V3 ULTIMATE +",
    sensor: "PAW3955Master",
    cidMid: "1,62",
    firmwareMark: "f1",
    usagePage: 65284,
    usage: 2,
    features: { noBottomButton: true, noDpiRGB: true, supportDpiToggle: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12a8,
    brand: "ATK",
    model: "ATK F1 V3 ULTIMATE +",
    sensor: "PAW3955Master",
    cidMid: "1,63",
    firmwareMark: "f1",
    usagePage: 65284,
    usage: 2,
    features: { noBottomButton: true, noDpiRGB: true, supportDpiToggle: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12a9,
    brand: "ATK",
    model: "ATK F1 V3 ULTIMATE +",
    sensor: "PAW3955Master",
    cidMid: "1,64",
    firmwareMark: "f1",
    usagePage: 65284,
    usage: 2,
    features: { noBottomButton: true, noDpiRGB: true, supportDpiToggle: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12ab,
    brand: "ATK",
    model: "ATK A9 NB ULTRA +",
    sensor: "PAW3955Master",
    cidMid: "2,129",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12af,
    brand: "ATK",
    model: "ATK Y9 Ultimate +",
    sensor: "PAW3955Master",
    cidMid: "1,66",
    firmwareMark: "y9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12b0,
    brand: "ATK",
    model: "ATK Z1 Ultimate 2.0 +",
    sensor: "PAW3955Master",
    cidMid: "1,67",
    firmwareMark: "z1",
    usagePage: 65284,
    usage: 2,
    features: { upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12b1,
    brand: "VXE",
    model: "VXE R2 SE NK",
    sensor: "PAW3315",
    cidMid: "2,19",
    firmwareMark: "r2",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noAthleticsMax: true, noFarDistance: true, noSensorAngle: true, noXyDpi: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12b3,
    brand: "ATK",
    model: "ATK A9 Ultimate Silent",
    sensor: "PAW3955Master",
    cidMid: "1,75",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true, supportDpiToggle: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12b4,
    brand: "ATK",
    model: "ATK X1 Ultimate 2.0 Silent",
    sensor: "PAW3955Master",
    cidMid: "1,76",
    firmwareMark: "x1",
    usagePage: 65284,
    usage: 2,
    features: { noBottomButton: true, supportDpiToggle: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12bf,
    brand: "VXE",
    model: "VXE R1SE+ Silent",
    sensor: "PAW3395SE",
    cidMid: "2,130",
    firmwareMark: "r1",
    usagePage: 65284,
    usage: 2,
    features: { noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12c6,
    brand: "ATK",
    model: "ATK A9 Wireless Charging",
    sensor: "PAW3955Master",
    cidMid: "1,71",
    firmwareMark: "a9",
    usagePage: 65284,
    usage: 2,
    features: { noDpiRGB: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12ce,
    brand: "ATK",
    model: "ATK PHANTOM ULTIMATE",
    sensor: "PAW3955Master",
    cidMid: "1,10",
    firmwareMark: "phantom",
    usagePage: 65285,
    usage: 1,
    features: { noBottomButton: true, noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12d0,
    brand: "ATK",
    model: "ATK A9 NB ULTRA",
    sensor: "PAW3950Ultra",
    cidMid: "2,20",
    firmwareMark: "a9",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12d2,
    brand: "VXE",
    model: "VXE V3 NK",
    sensor: "PAW3315",
    cidMid: "2,21",
    firmwareMark: "v3",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, middleDpiButton: true, noAthleticsMax: true, noDpiRGB: true, noFarDistance: true, noSensorAngle: true, noXyDpi: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12d7,
    brand: "ATK",
    model: "Flow 7",
    sensor: "PAW3950Ultra",
    cidMid: "2,131",
    firmwareMark: null,
    usagePage: 65284,
    usage: 2,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x12d9,
    brand: "ATK",
    model: "ATK X1 ULTIMATE 2.0+",
    sensor: "PAW3955Master",
    cidMid: "1,12",
    firmwareMark: "x1",
    usagePage: 65285,
    usage: 1,
    features: { noBottomButton: true, noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12dc,
    brand: "VXE",
    model: "VXE R1 SE+",
    sensor: "CORE26K",
    cidMid: "2,22",
    firmwareMark: "r1",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noAthleticsMax: true, noFarDistance: true, noSensorAngle: true, noXyDpi: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12de,
    brand: "ATK",
    model: "ATK X1 Ultra Max 2.0 + Tri-Mode",
    sensor: "PAW3955Master",
    cidMid: "1,13",
    firmwareMark: "x1",
    usagePage: 65285,
    usage: 1,
    features: { noBottomButton: true, noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12e1,
    brand: "VXE",
    model: "VXE T1",
    sensor: "PAW3950Ultra",
    cidMid: "2,23",
    firmwareMark: "m54",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12e3,
    brand: "ATK",
    model: "ATK U2 Plus NK",
    sensor: "PAW3950Ultra",
    cidMid: "2,25",
    firmwareMark: "u2",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noFarDistance: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12ec,
    brand: "ATK",
    model: "ATK X1 Air+",
    sensor: "PAW3955Master",
    cidMid: "1,14",
    firmwareMark: "x1",
    usagePage: 65285,
    usage: 1,
    features: { noBottomButton: true, noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12f1,
    brand: "ATK",
    model: "ATK A9 Ultimate +",
    sensor: "PAW3955Master",
    cidMid: "1,15",
    firmwareMark: "a9",
    usagePage: 65285,
    usage: 1,
    features: { noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12fa,
    brand: "ATK",
    model: "ATK F1 V3 ULTIMATE",
    sensor: "PAW3950Ultra",
    cidMid: "1,85",
    firmwareMark: "f1",
    usagePage: 65284,
    usage: 2,
    features: { noBottomButton: true, noDpiRGB: true, upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x12ff,
    brand: "ATK",
    model: "ATK X1 Ultra Max 2.0",
    sensor: "PAW3950DM",
    cidMid: "1,87",
    firmwareMark: "x1",
    usagePage: 65284,
    usage: 2,
    features: { upgradeTogether: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1300,
    brand: "ATK",
    model: "ATK A9 Plus NK",
    sensor: "PAW3950DM",
    cidMid: "2,26",
    firmwareMark: "a9",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noAthleticsMax: true, noDpiRGB: true, noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1301,
    brand: "ATK",
    model: "ATK A9 Pro Max 2.0 NK",
    sensor: "PAW3950DM",
    cidMid: "2,27",
    firmwareMark: "a9",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noDpiRGB: true, noFarDistance: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1304,
    brand: "ATK",
    model: "ATK F1 V3 ULTIMATE+",
    sensor: "PAW3955Master",
    cidMid: "1,17",
    firmwareMark: "f1",
    usagePage: 65285,
    usage: 1,
    features: { noBottomButton: true, noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1305,
    brand: "ATK",
    model: "ATK A9 3.0 NK",
    sensor: "CORE26K",
    cidMid: "2,29",
    firmwareMark: "a9",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noAthleticsMax: true, noDpiRGB: true, noFarDistance: true, noSensorAngle: true, noXyDpi: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1306,
    brand: "VXE",
    model: "VXE V3 PRO NK",
    sensor: "CORE26K",
    cidMid: "2,30",
    firmwareMark: "v3",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, middleDpiButton: true, noAthleticsMax: true, noDpiRGB: true, noFarDistance: true, noSensorAngle: true, noXyDpi: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1307,
    brand: "ATK",
    model: "ATK F1 V3 Ultra Max",
    sensor: "PAW3950Ultra",
    cidMid: "1,19",
    firmwareMark: "f1",
    usagePage: 65285,
    usage: 1,
    features: {  },
  },
  {
    vendorId: 0x373b,
    productId: 0x1308,
    brand: "ATK",
    model: "ATK F1 V3 ULTIMATE+",
    sensor: "PAW3955Master",
    cidMid: "1,18",
    firmwareMark: "f1",
    usagePage: 65285,
    usage: 1,
    features: { noBottomButton: true, noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x130e,
    brand: "ATK",
    model: "ATK X1 SE NK",
    sensor: "CORE26K",
    cidMid: "2,33",
    firmwareMark: "x1",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noAthleticsMax: true, noFarDistance: true, noSensorAngle: true, noXyDpi: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x130f,
    brand: "ATK",
    model: "ATK A9 SE 3.0 NK",
    sensor: "PAW3315",
    cidMid: "2,32",
    firmwareMark: "a9",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noAthleticsMax: true, noDpiRGB: true, noFarDistance: true, noSensorAngle: true, noXyDpi: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1310,
    brand: "VXE",
    model: "VXE R1 S NK",
    sensor: "PAW3315",
    cidMid: "2,31",
    firmwareMark: "r1s",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noAthleticsMax: true, noFarDistance: true, noSensorAngle: true, noXyDpi: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1311,
    brand: "VXE",
    model: "VXE R1N NK",
    sensor: "CORE26K",
    cidMid: "2,28",
    firmwareMark: "r1n",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noAthleticsMax: true, noFarDistance: true, noSensorAngle: true, noXyDpi: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1312,
    brand: "ATK",
    model: "ATK PHANTOM ULTIMATE",
    sensor: "PAW3955Master",
    cidMid: "1,21",
    firmwareMark: "phantom",
    usagePage: 65285,
    usage: 1,
    features: { noBottomButton: true, noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1314,
    brand: "ATK",
    model: "ATK A9 Ultimate",
    sensor: "PAW3950Ultra",
    cidMid: "1,22",
    firmwareMark: "a9",
    usagePage: 65285,
    usage: 1,
    features: { noDpiRGB: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1319,
    brand: "VXE",
    model: "VXE R1 SE+",
    sensor: "CORE26K",
    cidMid: "2,22",
    firmwareMark: "r1",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noAthleticsMax: true, noFarDistance: true, noSensorAngle: true, noXyDpi: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x131a,
    brand: "ATK",
    model: "ATK X1 S NK",
    sensor: "PAW3950Ultra",
    cidMid: "2,132",
    firmwareMark: "x1",
    usagePage: 65284,
    usage: 2,
    features: { noFarDistance: true, noZeroKeyDebounce: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x132b,
    brand: "ATK",
    model: "MAD R",
    sensor: "PAW3950Ultra",
    cidMid: "2,133",
    firmwareMark: "mad-r",
    usagePage: 65284,
    usage: 2,
    features: { noBottomButton: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1337,
    brand: "ATK",
    model: "ATK A9 Plus 3.0 NK",
    sensor: "PAW3950Ultra",
    cidMid: "2,34",
    firmwareMark: "a9",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noDpiRGB: true, noFarDistance: true },
  },
  {
    vendorId: 0x373b,
    productId: 0x1338,
    brand: "ATK",
    model: "ATK A9 Pro Max 3.0 NK",
    sensor: "PAW3950Ultra",
    cidMid: "2,35",
    firmwareMark: "a9",
    usagePage: 65285,
    usage: 1,
    features: { isNearlink: true, noDpiRGB: true, noFarDistance: true },
  },
];

const BY_VID_PID = new Map<string, AtkDeviceDescriptor[]>();
for (const device of ATK_MOUSE_DEVICES) {
  const key = `${device.vendorId}:${device.productId}`;
  const list = BY_VID_PID.get(key);
  if (list) list.push(device);
  else BY_VID_PID.set(key, [device]);
}

/** Every catalog entry sharing a USB vendor/product id (0, 1, or more). */
export function atkDevicesForHid(vendorId: number, productId: number): AtkDeviceDescriptor[] {
  return BY_VID_PID.get(`${vendorId}:${productId}`) ?? [];
}

/**
 * Resolve one device. Prefers an exact CID/MID match among the entries sharing
 * the USB id; falls back to the sole entry, else undefined when ambiguous.
 */
export function atkDeviceForHid(
  vendorId: number,
  productId: number,
  cidMid?: string | null,
): AtkDeviceDescriptor | undefined {
  const candidates = atkDevicesForHid(vendorId, productId);
  if (candidates.length <= 1) return candidates[0];
  if (cidMid) {
    const exact = candidates.find((d) => d.cidMid === cidMid);
    if (exact) return exact;
  }
  return undefined;
}

/** All catalog entries sharing one CID/MID (the key is ambiguous). */
export function atkDevicesForCidMid(cidMid: string): AtkDeviceDescriptor[] {
  return ATK_MOUSE_DEVICES.filter((d) => d.cidMid === cidMid);
}
